services:
  flask_app:
    container_name: flask_app
    image: flask_api:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_NAME=postgres
    depends_on:
      - flask_db
    secrets:
      - db_password

  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password

volumes:
  pgdata: {}

secrets:
  db_password:
    file: secrets/db_password.txt
